#!/bin/bash -e

myHome=$(dirname "$0")

make diff
./testdominion $3 >> first.out
mv first.out $myHome
gcov dominion.c 


./testdominion $3 >> second.out
mv second.out $myHome
gcov dominion.c 

diff -s -y first.out second.out >> diff.out
results=`tail -n 1 < diff.out`
if["$results" == "Files first.out and second.out are identical"]; 
	then
		echo "TEST PASSED"
	else
		echo "TEST FAILED"
fi